/**
* Migration script from 1.0.9 to 1.0.10
*/

ALTER TABLE param_func ADD COLUMN COUNTRY_NEW VARCHAR(10) NULL DEFAULT NULL AFTER COUNTRY;
ALTER TABLE param_func DROP FOREIGN KEY FK_PARAM_FUNC_COUNTRY;
ALTER TABLE param_func DROP INDEX FK_PARAM_FUNC_COUNTRY_idx;
UPDATE param_func PF SET COUNTRY_NEW=(SELECT LOCALE FROM country C WHERE C.ID=PF.COUNTRY);
ALTER TABLE param_func DROP INDEX U_PARAM_FUNC;
ALTER TABLE param_func DROP COLUMN COUNTRY;
ALTER TABLE param_func CHANGE COLUMN COUNTRY_NEW COUNTRY VARCHAR(10) NOT NULL;
ALTER TABLE param_func ADD UNIQUE INDEX U_PARAM_FUNC (TYPE ASC, COUNTRY ASC, LANGUAGE ASC, ENTRY ASC);

ALTER TABLE entities ADD COLUMN COUNTRY_NEW VARCHAR(10) NULL DEFAULT NULL AFTER COUNTRY;
ALTER TABLE entities DROP FOREIGN KEY FK_ENTITY_COUNTRY;
ALTER TABLE entities DROP INDEX FK_ENTITY_COUNTRY_idx;
UPDATE entities E SET COUNTRY_NEW=(SELECT LOCALE FROM country C WHERE C.ID=E.COUNTRY);
ALTER TABLE entities DROP COLUMN COUNTRY;
ALTER TABLE entities CHANGE COLUMN COUNTRY_NEW COUNTRY VARCHAR(10) NULL DEFAULT NULL;