/**
* Migration script from 1.0.0 to 1.0.1
*/

ALTER TABLE third_party ADD COLUMN TYPE_CORRESPONDANT INT(11) NOT NULL DEFAULT 1  AFTER ID_USER_TP;
ALTER TABLE third_party CHANGE COLUMN TYPE_CORRESPONDANT TYPE_CORRESPONDANT INT(11) NOT NULL;
