-- Change the max size of the address fields tfrom 38 to 100 --
ALTER TABLE `dco`.`address` 
CHANGE COLUMN `FIELD_ONE` `FIELD_ONE` VARCHAR(100) NOT NULL ,
CHANGE COLUMN `FIELD_TWO` `FIELD_TWO` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `FIELD_THREE` `FIELD_THREE` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `FIELD_FOUR` `FIELD_FOUR` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `FIELD_FIVE` `FIELD_FIVE` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `FIELD_SIX` `FIELD_SIX` VARCHAR(100) NULL DEFAULT NULL ,
CHANGE COLUMN `FIELD_SEVEN` `FIELD_SEVEN` VARCHAR(100) NULL DEFAULT NULL ;
