-- add a new field to fill other legal status/form on Entity
ALTER TABLE `dco`.`entities` 
ADD COLUMN `LEGAL_STATUS_OTHER` VARCHAR(50) NULL DEFAULT NULL AFTER `MERCANTILE_INSCRIPTION_NUMBER`;

-- add new fields to fill multi-roles of third party
ALTER TABLE `dco`.`third_party` 
CHANGE COLUMN `TYPE_CORRESPONDANT` `TYPE_CORRESPONDANT` INT(11) NULL DEFAULT NULL ,
ADD COLUMN `TYPE_CORRESPONDANT_TWO` INT(11) NULL DEFAULT NULL AFTER `TYPE_CORRESPONDANT`,
ADD COLUMN `TYPE_CORRESPONDANT_THREE` INT(11) NULL DEFAULT NULL AFTER `TYPE_CORRESPONDANT_TWO`;

-- add a new field into Account table to fill branch name.
ALTER TABLE `dco`.`account` 
ADD COLUMN `BRANCH_NAME` VARCHAR(50) NULL DEFAULT NULL AFTER `ID_COM_LANGUAGE`;

-- create a ne table to fill thirdParty citizenships
CREATE TABLE IF NOT EXISTS `dco`.`citizenship` (
  `THIRD_PARTY_ID` INT(11) NOT NULL,
  `COUNTRY` VARCHAR(50) NOT NULL,
  `VALUE` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`THIRD_PARTY_ID`, `COUNTRY`),
  CONSTRAINT `FK_THIRD_PARTY`
    FOREIGN KEY (`THIRD_PARTY_ID`)
    REFERENCES `dco`.`third_party` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;
  
