/**
* Migration script from 1.0.14 to 1.0.15
*/

/**
 * entities' attributes deleted 
 */
ALTER TABLE `dco`.`entities` 
DROP COLUMN `FAX`,
DROP COLUMN `MAIL`,
DROP COLUMN `TEL`;


/**
 * new association between third party and legal entity
 */
ALTER TABLE `dco`.`third_party` 
ADD COLUMN `LEGAL_ENTITY_ID` INT(11) NULL DEFAULT NULL AFTER `TYPE_CORRESPONDANT`,
ADD INDEX `FK_LEGAL_ENTITY_idx` (`LEGAL_ENTITY_ID` ASC);

ALTER TABLE `dco`.`third_party` 
ADD CONSTRAINT `FK_LEGAL_ENTITY`
  FOREIGN KEY (`LEGAL_ENTITY_ID`)
  REFERENCES `dco`.`legal_entity` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  
  /**
   * Drop column for third party fields : ID_OFFICE_ADRESS AUTORITY_ID and EXPIRATION_DATE_ID
  */
ALTER TABLE `dco`.`third_party` 
DROP FOREIGN KEY `FK_OFFICE_ADRESS`
ALTER TABLE `dco`.`third_party` 
DROP COLUMN `ID_OFFICE_ADRESS`,
DROP COLUMN `AUTORITY_ID`,
DROP COLUMN `EXPIRATION_DATE_ID`,
DROP INDEX `FK_OFFICE_ADRESS_idx`;


/**
 * new data for entity in a new page : signature card
 */
ALTER TABLE `dco`.`entities` 
ADD COLUMN `BOARD_RESOLUTION_DATE` DATETIME NULL DEFAULT NULL AFTER `CONTACT`,
ADD COLUMN `NOTARY_NAME` VARCHAR(50) NULL DEFAULT NULL AFTER `BOARD_RESOLUTION_DATE`,
ADD COLUMN `NOTARY_CITY` VARCHAR(50) NULL DEFAULT NULL AFTER `NOTARY_NAME`,
ADD COLUMN `ISSUANCE_DATE` DATETIME NULL DEFAULT NULL AFTER `NOTARY_CITY`,
ADD COLUMN `PUBLIC_DEED_REFERENCE` VARCHAR(50) NULL DEFAULT NULL AFTER `ISSUANCE_DATE`,
ADD COLUMN `MERCANTILE_INSCRIPTION_DATE` DATETIME NULL DEFAULT NULL AFTER `PUBLIC_DEED_REFERENCE`,
ADD COLUMN `MERCANTILE_INSCRIPTION_NUMBER` INT(3) NULL DEFAULT NULL AFTER `MERCANTILE_INSCRIPTION_DATE`;


/**
* Drop Registration Entity Date and Entity Nace Code columms: REGISTRATION_DATE and NACE_CODE
*/
ALTER TABLE `dco`.`entities` 
DROP COLUMN `REGISTRATION_DATE`,
DROP COLUMN `NACE_CODE`;


/**
* Add VAT registration number column: VAT_NUMBER_ACCOUNT
*
*/
ALTER TABLE `dco`.`account` 
ADD COLUMN `VAT_NUMBER_ACCOUNT` VARCHAR(100) NULL DEFAULT NULL AFTER `ID_COUNTRY`;

/**
* Add ID_COM_LANGUAGE column into the Account table and set as FK to the Language table 
*
*/
ALTER TABLE `dco`.`account` 
ADD COLUMN `ID_COM_LANGUAGE` INT(11) NULL DEFAULT NULL AFTER `VAT_NUMBER_ACCOUNT`,
ADD INDEX `FK_COM_LANGUAGE_idx` (`ID_COM_LANGUAGE` ASC);
ALTER TABLE `dco`.`account` 
ADD CONSTRAINT `FK_COM_LANGUAGE`
  FOREIGN KEY (`ID_COM_LANGUAGE`)
  REFERENCES `dco`.`language` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/**
  * Add COM_LANG_ENABLED column to allow the Country to use "communication language relationship" option 
  */
ALTER TABLE `dco`.`country` 
ADD COLUMN `COM_LANG_ENABLED` TINYINT(4) NOT NULL DEFAULT 0 AFTER `LEAGL_ENTITY`;

/** 
 * Add ID_ADDRESS column to save the Legal Entity address 
 */
ALTER TABLE `dco`.`legal_entity` 
ADD COLUMN `ID_ADDRESS` INT(11) NULL DEFAULT NULL AFTER `LABEL`,
ADD INDEX `FK_ID_ADDRESS_idx` (`ID_ADDRESS` ASC);
ALTER TABLE `dco`.`legal_entity` 
ADD CONSTRAINT `FK_ID_ADDRESS`
  FOREIGN KEY (`ID_ADDRESS`)
  REFERENCES `dco`.`address` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;