package com.bnpp.dco.business.dto;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountThirdParty generated by hbm2java
 */
@Entity
@Table(name = "account_third_party", catalog = "dco")
public class AccountThirdParty implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Account account;
    private ParamFunc paramFunc;
    private ThirdParty thirdParty;
    private Long amountLimit;
    private Integer statusAmountLimit;
    private String deviseAmountLimit;
    private Integer powerType;
    private Date boardResolutionDate;
    private String publicDeedReference;
    private Set authorizedList = new HashSet(0);
    
    private Signatory signatory;

    public AccountThirdParty() {
    }

    public AccountThirdParty(final Account account, final ThirdParty thirdParty) {
        this.account = account;
        this.thirdParty = thirdParty;
    }

    public AccountThirdParty(final Account account, final ParamFunc paramFunc, final ThirdParty thirdParty,
            final Long amountLimit) {
        this.account = account;
        this.paramFunc = paramFunc;
        this.thirdParty = thirdParty;
        this.amountLimit = amountLimit;
    }

    public AccountThirdParty(final Account account, final ParamFunc paramFunc, final ThirdParty thirdParty,
            final Long amountLimit, final Integer statusAmountLimit, final Integer powerType,
            final Date issuanceDate, final String publicDeedReference, final Date boardDate,
            final Date boardResolutionDate) {
        this.account = account;
        this.paramFunc = paramFunc;
        this.thirdParty = thirdParty;
        this.amountLimit = amountLimit;
        this.statusAmountLimit = statusAmountLimit;
        this.powerType = powerType;
        this.boardResolutionDate = boardResolutionDate;
        this.publicDeedReference = publicDeedReference;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_ACCOUNT", nullable = false)
    public Account getAccount() {
        return this.account;
    }

    public void setAccount(final Account account) {
        this.account = account;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_SIGNATURE_AUTHORIZATION")
    public ParamFunc getParamFunc() {
        return this.paramFunc;
    }

    public void setParamFunc(final ParamFunc paramFunc) {
        this.paramFunc = paramFunc;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_THIRD_PARTY", nullable = false)
    public ThirdParty getThirdParty() {
        return this.thirdParty;
    }

    public void setThirdParty(final ThirdParty thirdParty) {
        this.thirdParty = thirdParty;
    }

    @Column(name = "AMOUNT_LIMIT")
    public Long getAmountLimit() {
        return this.amountLimit;
    }

    public void setAmountLimit(final Long amountLimit) {
        this.amountLimit = amountLimit;
    }

    @Column(name = "STATUS_AMOUNT_LIMIT")
    public Integer getStatusAmountLimit() {
        return this.statusAmountLimit;
    }

    public void setStatusAmountLimit(final Integer statusAmountLimit) {
        this.statusAmountLimit = statusAmountLimit;
    }

    @Column(name = "POWER_TYPE")
    public Integer getPowerType() {
        return this.powerType;
    }

    public void setPowerType(final Integer powerType) {
        this.powerType = powerType;
    }

    @Column(name = "PUBLIC_DEED_REFERENCE", length = 50)
    public String getPublicDeedReference() {
        return this.publicDeedReference;
    }

    public void setPublicDeedReference(final String publicDeedReference) {
        this.publicDeedReference = publicDeedReference;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "BOARD_RESOLUTION_DATE", length = 19)
    public Date getBoardResolutionDate() {
        return this.boardResolutionDate;
    }

    public void setBoardResolutionDate(final Date boardResolutionDate) {
        this.boardResolutionDate = boardResolutionDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "accountThirdParty")
    public Set<AuthorizationThirdParty> getAuthorizedList() {
        return this.authorizedList;
    }

    public void setAuthorizedList(final Set authorizedList) {
        this.authorizedList = authorizedList;
    }

    @Column(name = "DEVISE_AMOUNT_LIMIT")
	public String getDeviseAmountLimit() {
		return deviseAmountLimit;
	}

	public void setDeviseAmountLimit(String deviseAmountLimit) {
		this.deviseAmountLimit = deviseAmountLimit;
	}

	/**
	 * @return the signatory
	 */
	public Signatory getSignatory() {
		return signatory;
	}

	/**
	 * @param signatory the signatory to set
	 */
	public void setSignatory(Signatory signatory) {
		this.signatory = signatory;
	}

}
