package com.bnpp.dco.business.dto;

// Generated 2 sept. 2013 15:02:16 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AccountForm generated by hbm2java
 */
@Entity
@Table(name = "account_form", catalog = "dco")
public class AccountForm implements java.io.Serializable {

    /** Serial. */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Entities entities;
    private Set accounts = new HashSet(0);

    public AccountForm() {
    }

    public AccountForm(final Entities entities) {
        this.entities = entities;
    }

    public AccountForm(final Entities entities, final Set accounts) {
        this.entities = entities;
        this.accounts = accounts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_ENTITY", nullable = false)
    public Entities getEntities() {
        return this.entities;
    }

    public void setEntities(final Entities entities) {
        this.entities = entities;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "accountForm")
    public Set<Account> getAccounts() {
        return this.accounts;
    }

    public void setAccounts(final Set accounts) {
        this.accounts = accounts;
    }

}
