package com.bnpp.dco.business.dto;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DateFormat generated by hbm2java
 */
@Entity
@Table(name = "date_format", catalog = "dco")
public class DateFormat implements java.io.Serializable {

    /** Serial. */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String label;
    private String labelDisplay;
    private String labelLong;
    private Set preferenceses = new HashSet(0);

    public DateFormat() {
    }

    public DateFormat(final String label, final Set preferenceses) {
        this.label = label;
        this.preferenceses = preferenceses;
    }

    public DateFormat(final String label, final String labelDisplay, final String labelLong,
            final Set preferenceses) {
        this.label = label;
        this.labelDisplay = labelDisplay;
        this.labelLong = labelLong;
        this.preferenceses = preferenceses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    @Column(name = "LABEL", length = 45)
    public String getLabel() {
        return this.label;
    }

    public void setLabel(final String label) {
        this.label = label;
    }

    @Column(name = "LABELDISPLAY", length = 45)
    public String getLabelDisplay() {
        return this.labelDisplay;
    }

    public void setLabelDisplay(final String labelDisplay) {
        this.labelDisplay = labelDisplay;
    }

    @Column(name = "LABELLONG", length = 45)
    public String getLabelLong() {
        return this.labelLong;
    }

    public void setLabelLong(final String labelLong) {
        this.labelLong = labelLong;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dateFormat")
    public Set<Preferences> getPreferenceses() {
        return this.preferenceses;
    }

    public void setPreferenceses(final Set preferenceses) {
        this.preferenceses = preferenceses;
    }

}
