package com.bnpp.dco.business.dto;

// Generated 10 sept. 2013 15:39:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParamTechId generated by hbm2java
 */
@Embeddable
public class ParamTechId implements java.io.Serializable {

    private int entity;
    private String name;
    private String value;

    public ParamTechId() {
    }

    public ParamTechId(final int entity, final String name, final String value) {
        this.entity = entity;
        this.name = name;
        this.value = value;
    }

    @Column(name = "ENTITY", nullable = false)
    public int getEntity() {
        return this.entity;
    }

    public void setEntity(final int entity) {
        this.entity = entity;
    }

    @Column(name = "NAME", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    @Column(name = "VALUE", nullable = false, length = 100)
    public String getValue() {
        return this.value;
    }

    public void setValue(final String value) {
        this.value = value;
    }

    @Override
    public boolean equals(final Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof ParamTechId)) {
            return false;
        }
        final ParamTechId castOther = (ParamTechId) other;

        return this.getEntity() == castOther.getEntity()
                && (this.getName().equals(castOther.getName()) || this.getName() != null
                        && castOther.getName() != null && this.getName().equals(castOther.getName()))
                && (this.getValue().equals(castOther.getValue()) || this.getValue() != null
                        && castOther.getValue() != null && this.getValue().equals(castOther.getValue()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getEntity();
        result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
        result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
        return result;
    }

}
