package com.bnpp.dco.business.dto;

// Generated 10 sept. 2013 15:39:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ParamTech generated by hbm2java
 */
@Entity
@Table(name = "param_tech", catalog = "dco")
public class ParamTech implements java.io.Serializable {

    private ParamTechId id;
    private Entities entities;

    public ParamTech() {
    }

    public ParamTech(final ParamTechId id, final Entities entities) {
        this.id = id;
        this.entities = entities;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "entity", column = @Column(name = "ENTITY", nullable = false)),
            @AttributeOverride(name = "name", column = @Column(name = "NAME", nullable = false, length = 50)),
            @AttributeOverride(name = "value", column = @Column(name = "VALUE", nullable = false, length = 100))})
    public ParamTechId getId() {
        return this.id;
    }

    public void setId(final ParamTechId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ENTITY", nullable = false, insertable = false, updatable = false)
    public Entities getEntities() {
        return this.entities;
    }

    public void setEntities(final Entities entities) {
        this.entities = entities;
    }

}
