package com.bnpp.dco.business.dto;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParamFuncType generated by hbm2java
 */
@Entity
@Table(name = "param_func_type", catalog = "dco")
public class ParamFuncType implements java.io.Serializable {

    /** Serial. */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String labelDefault;
    private Set paramFuncs = new HashSet(0);

    public ParamFuncType() {
    }

    public ParamFuncType(final String labelDefault) {
        this.labelDefault = labelDefault;
    }

    public ParamFuncType(final String labelDefault, final Set paramFuncs) {
        this.labelDefault = labelDefault;
        this.paramFuncs = paramFuncs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    @Column(name = "LABEL_DEFAULT", nullable = false, length = 100)
    public String getLabelDefault() {
        return this.labelDefault;
    }

    public void setLabelDefault(final String labelDefault) {
        this.labelDefault = labelDefault;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "paramFuncType")
    public Set<ParamFunc> getParamFuncs() {
        return this.paramFuncs;
    }

    public void setParamFuncs(final Set paramFuncs) {
        this.paramFuncs = paramFuncs;
    }

}
