package com.bnpp.dco.business.dto;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Preferences generated by hbm2java
 */
@Entity
@Table(name = "preferences", catalog = "dco")
public class Preferences implements java.io.Serializable {

    /** Serial. */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Language language;
    private DateFormat dateFormat;
    private String formatAmount;
    private Set users = new HashSet(0);

    public Preferences() {
    }

    public Preferences(final Language language, final DateFormat dateFormat, final String formatAmount) {
        this.language = language;
        this.dateFormat = dateFormat;
        this.formatAmount = formatAmount;
    }

    public Preferences(final Language language, final DateFormat dateFormat, final String formatAmount,
            final Set users) {
        this.language = language;
        this.dateFormat = dateFormat;
        this.formatAmount = formatAmount;
        this.users = users;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LANGUAGE", nullable = false)
    public Language getLanguage() {
        return this.language;
    }

    public void setLanguage(final Language language) {
        this.language = language;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FORMAT_DATE", nullable = false)
    public DateFormat getDateFormat() {
        return this.dateFormat;
    }

    public void setDateFormat(final DateFormat dateFormat) {
        this.dateFormat = dateFormat;
    }

    @Column(name = "FORMAT_AMOUNT", nullable = false, length = 30)
    public String getFormatAmount() {
        return this.formatAmount;
    }

    public void setFormatAmount(final String formatAmount) {
        this.formatAmount = formatAmount;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "preferences")
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(final Set users) {
        this.users = users;
    }

}
