package com.bnpp.dco.business.dto;

// Generated 16 oct. 2013 10:12:51 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThirdParty generated by hbm2java
 */
@Entity
@Table(name = "third_party", catalog = "dco")
public class ThirdParty implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 4713506457331723303L;
    private Integer id;
    private String legalEntityName;
    private String positionName;
    private Address addressByIdHomeAdress;
    private User user;
    private String name;
    private String firstName;
    private Date birthDate;
    private String birthPlace;
    private String mail;
    private String tel;
    private String fax;
    private String referenceId;
    private String nationality;
    private Integer correspondantType;
    private Integer correspondantTypeTwo;
    private Integer correspondantTypeThree;
    private Set entitieses = new HashSet(0);
    private Set accountThirdParties = new HashSet(0);
    private Set citizenships = new HashSet(0);

    public ThirdParty() {
    }

    public ThirdParty(final Address addressByIdHomeAdress, final User user, final String name,
            final String firstName, final Integer correspondantType) {
        this.addressByIdHomeAdress = addressByIdHomeAdress;
        this.user = user;
        this.name = name;
        this.firstName = firstName;
        this.correspondantType = correspondantType;
    }

    public ThirdParty(final String positionName, final String legalEntityName,
            final Address addressByIdHomeAdress, final User user, final String name, final String firstName,
            final Date birthDate, final String birthPlace, final String mail, final String tel, final String fax,
            final String referenceId, final String nationality, final Integer correspondantType,
            final Integer correspondantTypeTwo, final Integer correspondantTypeThree, final Set entitieses,
            final Set accountThirdParties, final Set citizenships) {
        this.legalEntityName = legalEntityName;
        this.positionName = positionName;
        this.addressByIdHomeAdress = addressByIdHomeAdress;
        this.user = user;
        this.name = name;
        this.firstName = firstName;
        this.birthDate = birthDate;
        this.birthPlace = birthPlace;
        this.mail = mail;
        this.tel = tel;
        this.fax = fax;
        this.referenceId = referenceId;
        this.nationality = nationality;
        this.correspondantType = correspondantType;
        this.correspondantTypeTwo = correspondantTypeTwo;
        this.correspondantTypeThree = correspondantTypeThree;
        this.entitieses = entitieses;
        this.accountThirdParties = accountThirdParties;
        this.citizenships = citizenships;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    @Column(name = "POSITION_NAME", length = 50)
    public String getPositionName() {
        return this.positionName;
    }

    public void setPositionName(final String positionName) {
        this.positionName = positionName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_HOME_ADRESS", nullable = false)
    public Address getAddressByIdHomeAdress() {
        return this.addressByIdHomeAdress;
    }

    public void setAddressByIdHomeAdress(final Address addressByIdHomeAdress) {
        this.addressByIdHomeAdress = addressByIdHomeAdress;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_USER_TP", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(final User user) {
        this.user = user;
    }

    @Column(name = "NAME", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    @Column(name = "FIRST_NAME", nullable = false, length = 100)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(final String firstName) {
        this.firstName = firstName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "BIRTH_DATE", length = 19)
    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(final Date birthDate) {
        this.birthDate = birthDate;
    }

    @Column(name = "BIRTH_PLACE", length = 100)
    public String getBirthPlace() {
        return this.birthPlace;
    }

    public void setBirthPlace(final String birthPlace) {
        this.birthPlace = birthPlace;
    }

    @Column(name = "MAIL", length = 100)
    public String getMail() {
        return this.mail;
    }

    public void setMail(final String mail) {
        this.mail = mail;
    }

    @Column(name = "TEL", length = 100)
    public String getTel() {
        return this.tel;
    }

    public void setTel(final String tel) {
        this.tel = tel;
    }

    @Column(name = "FAX", length = 45)
    public String getFax() {
        return this.fax;
    }

    public void setFax(final String fax) {
        this.fax = fax;
    }

    @Column(name = "REFERENCE_ID", length = 45)
    public String getReferenceId() {
        return this.referenceId;
    }

    public void setReferenceId(final String referenceId) {
        this.referenceId = referenceId;
    }

    @Column(name = "NATIONALITY", length = 10)
    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(final String nationality) {
        this.nationality = nationality;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "thirdParty")
    public Set<AccountThirdParty> getAccountThirdParties() {
        return this.accountThirdParties;
    }

    public void setAccountThirdParties(final Set accountThirdParties) {
        this.accountThirdParties = accountThirdParties;
    }

    //@OneToMany(fetch = FetchType.LAZY, mappedBy = "thirdParty")
    public Set<Citizenship> getCitizenships() {
        return this.citizenships;
    }

    public void setCitizenships(final Set citizenships) {
        this.citizenships = citizenships;
    }

    @Column(name = "TYPE_CORRESPONDANT", nullable = true)
    public Integer getCorrespondantType() {
        return this.correspondantType;
    }

    public void setCorrespondantType(final Integer correspondantType) {
        this.correspondantType = correspondantType;
    }

    @Column(name = "TYPE_CORRESPONDANT_TWO", nullable = true)
    public Integer getCorrespondantTypeTwo() {
        return this.correspondantTypeTwo;
    }

    public void setCorrespondantTypeTwo(final Integer correspondantTypeTwo) {
        this.correspondantTypeTwo = correspondantTypeTwo;
    }

    @Column(name = "TYPE_CORRESPONDANT_THREE", nullable = true)
    public Integer getCorrespondantTypeThree() {
        return this.correspondantTypeThree;
    }

    public void setCorrespondantTypeThree(final Integer correspondantTypeThree) {
        this.correspondantTypeThree = correspondantTypeThree;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "thirdParty")
    public Set<Entities> getEntitieses() {
        return this.entitieses;
    }

    public void setEntitieses(final Set entitieses) {
        this.entitieses = entitieses;
    }

    /**
     * @return the legalEntityName
     */
    @Column(name = "LEGAL_ENTITY_NAME", length = 50)
    public String getLegalEntityName() {
        return this.legalEntityName;
    }

    /**
     * @param legalEntityName the legalEntityName to set
     */
    public void setLegalEntityName(final String legalEntityName) {
        this.legalEntityName = legalEntityName;
    }

}
