package com.bnpp.dco.business.dto;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "dco")
public class User implements java.io.Serializable {

    /** Serial. */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Preferences preferences;
    private String login;
    private String password;
    private String firstName;
    private String lastName;
    private int profile;
    private String email;
    private String tel;
    private Date datePassword;
    private String password2;
    private String password3;
    private int lockLevel;
    private boolean locked;
    private boolean xbasV2;
    private boolean deleted;
    private Set entitieses = new HashSet(0);
    private Set thirdParties = new HashSet(0);
    private Set legalEntities = new HashSet(0);
    private Set roles = new HashSet(0);

    public User() {
    }

    public User(final String login, final String password, final String firstName, final String lastName,
            final int profile, final String email, final int lockLevel, final boolean locked) {
        this.login = login;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.profile = profile;
        this.email = email;
        this.lockLevel = lockLevel;
        this.locked = locked;
    }

    public User(final Preferences preferences, final String login, final String password, final String firstName,
            final String lastName, final int profile, final String email, final String tel,
            final Date datePassword, final String password2, final String password3, final int lockLevel,
            final boolean locked, final Set entitieses, final Set thirdParties, final Set legalEntities,
            final Set roles) {
        this.preferences = preferences;
        this.login = login;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.profile = profile;
        this.email = email;
        this.tel = tel;
        this.datePassword = datePassword;
        this.password2 = password2;
        this.password3 = password3;
        this.lockLevel = lockLevel;
        this.locked = locked;
        this.entitieses = entitieses;
        this.thirdParties = thirdParties;
        this.legalEntities = legalEntities;
        this.roles = roles;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PREFERENCES")
    public Preferences getPreferences() {
        return this.preferences;
    }

    public void setPreferences(final Preferences preferences) {
        this.preferences = preferences;
    }

    @Column(name = "LOGIN", nullable = false, length = 50)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(final String login) {
        this.login = login;
    }

    @Column(name = "PASSWORD", nullable = false, length = 128)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(final String password) {
        this.password = password;
    }

    @Column(name = "FIRST_NAME", nullable = false, length = 100)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(final String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "LAST_NAME", nullable = false, length = 100)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(final String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "PROFILE", nullable = false)
    public int getProfile() {
        return this.profile;
    }

    public void setProfile(final int profile) {
        this.profile = profile;
    }

    @Column(name = "EMAIL", nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(final String email) {
        this.email = email;
    }

    @Column(name = "TEL", length = 45)
    public String getTel() {
        return this.tel;
    }

    public void setTel(final String tel) {
        this.tel = tel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DATE_PASSWORD", length = 19)
    public Date getDatePassword() {
        return this.datePassword;
    }

    public void setDatePassword(final Date datePassword) {
        this.datePassword = datePassword;
    }

    @Column(name = "PASSWORD2", length = 128)
    public String getPassword2() {
        return this.password2;
    }

    public void setPassword2(final String password2) {
        this.password2 = password2;
    }

    @Column(name = "PASSWORD3", length = 128)
    public String getPassword3() {
        return this.password3;
    }

    public void setPassword3(final String password3) {
        this.password3 = password3;
    }

    @Column(name = "LOCK_LEVEL", nullable = false)
    public int getLockLevel() {
        return this.lockLevel;
    }

    public void setLockLevel(final int lockLevel) {
        this.lockLevel = lockLevel;
    }

    @Column(name = "LOCKED", nullable = false)
    public boolean isLocked() {
        return this.locked;
    }

    public void setLocked(final boolean locked) {
        this.locked = locked;
    }
    
    @Column(name = "XBAS", nullable = false)
    public boolean isXbasV2() {
		return xbasV2;
	}

	public void setXbasV2(boolean xbasV2) {
		this.xbasV2 = xbasV2;
	}

	@Column(name = "DELETE_DATA", nullable = false)
	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
	
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "user_entity", catalog = "dco", joinColumns = {@JoinColumn(name = "USER", nullable = false, updatable = false)}, inverseJoinColumns = {@JoinColumn(name = "ENTITY", nullable = false, updatable = false)})
    public Set<Entities> getEntitieses() {
        return this.entitieses;
    }

    public void setEntitieses(final Set entitieses) {
        this.entitieses = entitieses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<ThirdParty> getThirdParties() {
        return this.thirdParties;
    }

    public void setThirdParties(final Set thirdParties) {
        this.thirdParties = thirdParties;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "user_legal_entity", catalog = "dco", joinColumns = {@JoinColumn(name = "USER", nullable = false, updatable = false)}, inverseJoinColumns = {@JoinColumn(name = "LEGAL_ENTITY", nullable = false, updatable = false)})
    public Set<LegalEntity> getLegalEntities() {
        return this.legalEntities;
    }

    public void setLegalEntities(final Set legalEntities) {
        this.legalEntities = legalEntities;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "user_role", catalog = "dco", joinColumns = {@JoinColumn(name = "USER", nullable = false, updatable = false)}, inverseJoinColumns = {@JoinColumn(name = "ROLE", nullable = false, updatable = false)})
    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(final Set roles) {
        this.roles = roles;
    }
}
